#%RAML 1.0 NamedExample
value:

  -

   Id: 1
   Name: Alekhya
   Email: chandugollapudi0277@gmail.com
   Age: 21
   City: Guntur
   Project: Employee Tracking System
   Manager: abcde

  -

   Id: 2
   Name: Anudeep
   Email: anudeep@gmail.com
   Age: 22
   City: Hyderabad
   Project: Employee Tracking System
   Manager: Ragalatha
  -

   Id: 3
   Name: Balu
   Email: Balu@gmail.com
   Age: 23
   City: Hyderabad
   Project: Employee Tracking System
   Manager: Vishnu

 